_wandb:
    value:
        cli_version: 0.26.1
        e:
            g19y8lwxbp60lxabkphwf24jkjcynvcl:
                codePath: notebooks/W&bCheckList.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "489549008896"
                        used: "422359973888"
                email: kanhapandey53@gmail.com
                executable: C:\Users\kanha\OneDrive\Desktop\Conda\MachLeData\python.exe
                git:
                    commit: f2c8748143c7decd447b22454bbbe36df57b70e5
                    remote: https://github.com/liviazobeli/MachLeData.git
                gpu: NVIDIA GeForce GTX 1650 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650 Ti
                      uuid: GPU-a19edbea-9442-6b3a-c953-29c58d1dc96a
                host: LAPTOP-4PFJMCAP
                memory:
                    total: "8419020800"
                os: Windows-10-10.0.26200-SP0
                program: notebooks/W&bCheckList.ipynb
                python: CPython 3.9.25
                root: C:\Users\kanha\Documents\MachLeData\notebooks
                startedAt: "2026-05-13T13:21:46.094580Z"
                writerId: g19y8lwxbp60lxabkphwf24jkjcynvcl
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.9.25
            "5": 0.26.1
            "8":
                - 1
                - 3
            "12": 0.26.1
            "13": windows-amd64
        visualize:
            Charts/Average_RMSE:
                panel_config:
                    fieldSettings:
                        label: Model
                        value: RMSE
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: Final Average RMSE (Lower is Better)
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Charts/Average_RMSE_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            Charts/DA_Consistency:
                panel_config:
                    fieldSettings:
                        x: Ground_Truth
                        "y": Prediction
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: DA-V2 Consistency (Meters)
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Charts/DA_Consistency_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            Charts/MiDaS_Consistency:
                panel_config:
                    fieldSettings:
                        x: Ground_Truth
                        "y": Prediction
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: MiDaS Consistency (Meters)
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Charts/MiDaS_Consistency_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
